/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author soyidwahyud
 */
public class FrmBooking extends javax.swing.JFrame {

    /**
     * Creates new form FrmBooking
     */
    public boolean click = false;
    public FrmBooking() {
        initComponents();
        kosongkan();
        tampilkanData();
    }
    public void kosongkan() {
        TextIdbooking.setText("0");
        Textnama.setText("");
        TextMaskapai.setText("");
        Textkode.setText("");
        Textkelas.setText("");
        Textstatus.setText("");
        TextHarga.setText("");
        Textcredit.setText("");
        Combopayment.setSelectedIndex(0);
        click = false;
    }
    public void tampilkanData(){
        String [] kolom = {"id booking","Nama","Nama Maskapai","kode kursi","kelas","status", "total harga","tipe payment", "no credit"};
        ArrayList<Booking> list = new Booking().getAll();
        Object row[] = new Object[9];
        TableBooking.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getIdBooking();
            row[1] = list.get(i).getData().getNama();
            row[2] = list.get(i).getMaskapai().getNama();
            row[3] = list.get(i).getKodeKursi();
            row[4] = list.get(i).getKelas();
            row[5] = list.get(i).getStatus();
            row[6] = list.get(i).getTotalharga();
            row[7] = list.get(i).getTipePayment();
            row[8] = list.get(i).getNoCredit();
            ((DefaultTableModel)TableBooking.getModel()).addRow(row);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIDbooking1 = new javax.swing.JLabel();
        TextIdbooking = new javax.swing.JTextField();
        jkode = new javax.swing.JLabel();
        Textkode = new javax.swing.JTextField();
        jkelas = new javax.swing.JLabel();
        Textkelas = new javax.swing.JTextField();
        jstatus = new javax.swing.JLabel();
        Textstatus = new javax.swing.JTextField();
        jbooking = new javax.swing.JLabel();
        jharga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBooking = new javax.swing.JTable();
        TextHarga = new javax.swing.JTextField();
        jHapus = new javax.swing.JButton();
        jtipepayment = new javax.swing.JLabel();
        Combopayment = new javax.swing.JComboBox<>();
        jcredit = new javax.swing.JLabel();
        Textcredit = new javax.swing.JTextField();
        jnama = new javax.swing.JLabel();
        Textnama = new javax.swing.JTextField();
        jmaskapai = new javax.swing.JLabel();
        TextMaskapai = new javax.swing.JTextField();
        jtipepayment1 = new javax.swing.JLabel();
        TextPayment = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Booking = new javax.swing.JMenuItem();
        Data = new javax.swing.JMenuItem();
        Jadwal = new javax.swing.JMenuItem();
        Maskapai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIDbooking1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jIDbooking1.setText("ID booking");

        TextIdbooking.setEditable(false);
        TextIdbooking.setEnabled(false);

        jkode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jkode.setText("Kode kursi");

        jkelas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jkelas.setText("Kelas");

        jstatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jstatus.setText("Status");

        jbooking.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbooking.setText("Pengaturan Booking");

        jharga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jharga.setText("Total Harga");

        TableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBooking);

        jHapus.setText("Hapus");

        jtipepayment.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtipepayment.setText("Tipe Payment");

        Combopayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combopayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CombopaymentMouseClicked(evt);
            }
        });

        jcredit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jcredit.setText("No credit");

        jnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jnama.setText("Nama");

        jmaskapai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jmaskapai.setText("Nama maskapai");

        jtipepayment1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtipepayment1.setText("Tipe Payment");

        jMenu4.setText("File");

        jMenuItem8.setText("Exit");
        jMenu4.add(jMenuItem8);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        Booking.setText("FrmBooking");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });
        jMenu5.add(Booking);

        Data.setText("FrmData");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });
        jMenu5.add(Data);

        Jadwal.setText("FrmJadwal");
        Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalActionPerformed(evt);
            }
        });
        jMenu5.add(Jadwal);

        Maskapai.setText("FrmMaskapai");
        Maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaskapaiActionPerformed(evt);
            }
        });
        jMenu5.add(Maskapai);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jkode)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Textkode, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jkelas)
                            .addGap(62, 62, 62)
                            .addComponent(Textkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jnama)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Textnama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jmaskapai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                            .addComponent(TextMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jIDbooking1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextIdbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jstatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Textstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jharga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtipepayment)
                            .addComponent(jcredit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textcredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combopayment, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jtipepayment1)
                        .addGap(18, 18, 18)
                        .addComponent(TextPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jHapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbooking)
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jbooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIDbooking1)
                            .addComponent(TextIdbooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnama)
                            .addComponent(Textnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmaskapai)
                            .addComponent(TextMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jkode)
                            .addComponent(Textkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jkelas)
                            .addComponent(Textkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jstatus)
                            .addComponent(Textstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jharga)
                            .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtipepayment1)
                            .addComponent(TextPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtipepayment)
                            .addComponent(Combopayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcredit)
                            .addComponent(Textcredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jHapus)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
        FrmBooking frmBooking = new FrmBooking();
        frmBooking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookingActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
        FrmData frmdata = new FrmData();
        frmdata.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DataActionPerformed

    private void JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalActionPerformed
        // TODO add your handling code here:
        FrmJadwal frmjadwal = new FrmJadwal();
        frmjadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JadwalActionPerformed

    private void MaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaskapaiActionPerformed
        // TODO add your handling code here:
        FrmMaskapai frmmaskapai = new FrmMaskapai();
        frmmaskapai.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MaskapaiActionPerformed

    private void TableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBookingMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TableBooking.getModel();
        int row = TableBooking.getSelectedRow();
        Booking b = new Booking().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        TextIdbooking.setText(String.valueOf(b.getIdBooking()));
        Textnama.setText(b.getData().getNama());
        Combopayment.getModel().setSelectedItem(b.getTipePayment());
        Textkelas.setText(b.getKelas());
        Textstatus.setText(b.getStatus());
        TextHarga.setText(String.valueOf(b.getTotalharga()));
        Textcredit.setText(String.valueOf(b.getNoCredit()));
        click = true;
    }//GEN-LAST:event_TableBookingMouseClicked

    private void CombopaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CombopaymentMouseClicked
        // TODO add your handling code here:
        Booking b = (Booking)Combopayment.getSelectedItem();
        TextPayment.setText(b.getTipePayment());
    }//GEN-LAST:event_CombopaymentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Booking;
    private javax.swing.JComboBox<String> Combopayment;
    private javax.swing.JMenuItem Data;
    private javax.swing.JMenuItem Jadwal;
    private javax.swing.JMenuItem Maskapai;
    private javax.swing.JTable TableBooking;
    private javax.swing.JTextField TextHarga;
    private javax.swing.JTextField TextIdbooking;
    private javax.swing.JTextField TextMaskapai;
    private javax.swing.JTextField TextPayment;
    private javax.swing.JTextField Textcredit;
    private javax.swing.JTextField Textkelas;
    private javax.swing.JTextField Textkode;
    private javax.swing.JTextField Textnama;
    private javax.swing.JTextField Textstatus;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jIDbooking1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbooking;
    private javax.swing.JLabel jcredit;
    private javax.swing.JLabel jharga;
    private javax.swing.JLabel jkelas;
    private javax.swing.JLabel jkode;
    private javax.swing.JLabel jmaskapai;
    private javax.swing.JLabel jnama;
    private javax.swing.JLabel jstatus;
    private javax.swing.JLabel jtipepayment;
    private javax.swing.JLabel jtipepayment1;
    // End of variables declaration//GEN-END:variables
}
