/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soyidwahyud
 */
public class FrmJadwal extends javax.swing.JFrame {
    /**
     * Creates new form FrmJadwal
     */
    public Boolean click = false;
    public FrmJadwal() {
        initComponents();
        Kosongkan();
        tampilkanData();
    }
    public void Kosongkan(){
        jIdjadwal.setText("0");
        inputDeparture.setText("");
        inputDestination.setText("");
        inputDate.setText("");
        click = false;
    }
    public void tampilkanData(){
        String [] Kolom = {"Id","Departure","Destination","Tanggal"};
        ArrayList<Jadwal> List = new Jadwal().getAll();
        Object row[] = new Object[4];
        jTable1.setModel(new DefaultTableModel(new Object[][]{}, Kolom));
        for (int i = 0; i<List.size(); i++) {
            row[0] = List.get(i).getIdjadwal();
            row[1] = List.get(i).getDepature();
            row[2] = List.get(i).getDestination();
            row[3] = List.get(i).getDeparturedate();
            ((DefaultTableModel)jTable1.getModel()).addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIDjadwal1 = new javax.swing.JLabel();
        jIdjadwal = new javax.swing.JTextField();
        jDeparture = new javax.swing.JLabel();
        inputDeparture = new javax.swing.JTextField();
        jDestination = new javax.swing.JLabel();
        inputDestination = new javax.swing.JTextField();
        jDate = new javax.swing.JLabel();
        inputDate = new javax.swing.JTextField();
        jjadwal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jsimpan1 = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Booking = new javax.swing.JMenuItem();
        Data = new javax.swing.JMenuItem();
        Jadwal = new javax.swing.JMenuItem();
        Maskapai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIDjadwal1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jIDjadwal1.setText("ID jadwal");

        jIdjadwal.setEditable(false);
        jIdjadwal.setEnabled(false);

        jDeparture.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jDeparture.setText("Departure");

        jDestination.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jDestination.setText("Destination");

        jDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jDate.setText("Departure Date");

        jjadwal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jjadwal.setText("Pengaturan jadwal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jsimpan1.setText("Simpan");
        jsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsimpan1ActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jMenu4.setText("File");

        jMenuItem8.setText("Exit");
        jMenu4.add(jMenuItem8);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        Booking.setText("FrmBooking");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });
        jMenu5.add(Booking);

        Data.setText("FrmData");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });
        jMenu5.add(Data);

        Jadwal.setText("FrmJadwal");
        Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalActionPerformed(evt);
            }
        });
        jMenu5.add(Jadwal);

        Maskapai.setText("FrmMaskapai");
        Maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaskapaiActionPerformed(evt);
            }
        });
        jMenu5.add(Maskapai);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jjadwal)
                            .addGap(119, 119, 119))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDeparture)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jIDjadwal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jIdjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDestination)
                                .addGap(62, 62, 62)
                                .addComponent(inputDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jsimpan1)
                .addGap(63, 63, 63)
                .addComponent(Tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jHapus)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jjadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIDjadwal1)
                    .addComponent(jIdjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeparture)
                    .addComponent(inputDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDestination)
                    .addComponent(inputDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDate)
                    .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsimpan1)
                    .addComponent(Tambah)
                    .addComponent(jHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
        FrmBooking frmBooking = new FrmBooking();
        frmBooking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookingActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
        FrmData frmdata = new FrmData();
        frmdata.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DataActionPerformed

    private void JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalActionPerformed
        // TODO add your handling code here:
        FrmJadwal frmjadwal = new FrmJadwal();
        frmjadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JadwalActionPerformed

    private void MaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaskapaiActionPerformed
        // TODO add your handling code here:
        FrmMaskapai frmmaskapai = new FrmMaskapai();
        frmmaskapai.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MaskapaiActionPerformed

    private void jsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsimpan1ActionPerformed
        // TODO add your handling code here:
            Jadwal jadwal = new Jadwal();
            jadwal.setIdjadwal(Integer.parseInt(jIdjadwal.getText()));
            jadwal.setDepature(inputDeparture.getText());
            jadwal.setDestination(inputDestination.getText());
            jadwal.setDeparturedate(inputDate.getText());
            //System.out.println(jadwal.getIdjadwal());
            jadwal.save();
            jIdjadwal.setText(Integer.toString(jadwal.getIdjadwal()));
            tampilkanData();
        
    }//GEN-LAST:event_jsimpan1ActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        Kosongkan();
    }//GEN-LAST:event_TambahActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        if (click) {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int row = jTable1.getSelectedRow();
            Jadwal j = new Jadwal().getById(Integer.parseInt(model.getValueAt(row,0).toString()));
            j.delete();
            Kosongkan();
            tampilkanData();
        } else {
            
        }
        
    }//GEN-LAST:event_jHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        Jadwal j = new Jadwal().getById(Integer.parseInt(model.getValueAt(row,0).toString()));
        jIdjadwal.setText(String.valueOf(j.getIdjadwal()));
        inputDeparture.setText(j.getDepature());
        inputDate.setText(j.getDeparturedate());
        inputDestination.setText(j.getDestination());
        click = true;
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Booking;
    private javax.swing.JMenuItem Data;
    private javax.swing.JMenuItem Jadwal;
    private javax.swing.JMenuItem Maskapai;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField inputDate;
    private javax.swing.JTextField inputDeparture;
    private javax.swing.JTextField inputDestination;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jDeparture;
    private javax.swing.JLabel jDestination;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jIDjadwal1;
    private javax.swing.JTextField jIdjadwal;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jjadwal;
    private javax.swing.JButton jsimpan1;
    // End of variables declaration//GEN-END:variables
}
