/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author soyidwahyud
 */
public class FrmMaskapai extends javax.swing.JFrame {

    /**
     * Creates new form FrmMaskapai
     */
    public boolean click = false;
    public FrmMaskapai() {
        initComponents();
        kosongkan();
        setComboJadwal();
        tampilkanData();
    }
    public void kosongkan() {
        textIdMaskapai.setText("0");
        textKeb.setText("");
        textKedatangan.setText("");
        textNama.setText("");
        textWaktuDatang.setText("");
        textwaktuBerangkat.setText("");
        textHargaBisnis.setText("");
        textHargaEkonomi.setText("");
        click = false;
    }
    public void tampilkanData(){
        String [] kolom = {"id","Maskapai","from","jam depart","dertination","jam sampai","Harga Bisnis", "Harga Ekonomi"};
        ArrayList<Maskapai> list = new Maskapai().getAll();
        Object row[] = new Object[8];
        TableMaskapai.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getIdMaskapai();
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getJadwal().getDepature();
            row[3] = list.get(i).getWaktuDeparture();
            row[4] = list.get(i).getJadwal().getDestination();
            row[5] = list.get(i).getWaktuDestination();
            row[6] = list.get(i).getHarga_bis();
            row[7] = list.get(i).getHarga_eko();
            ((DefaultTableModel)TableMaskapai.getModel()).addRow(row);
        }
    }
    public void setComboJadwal(){
        comboJadwal.setModel(new DefaultComboBoxModel(new Jadwal().getAll().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIDmaskapai1 = new javax.swing.JLabel();
        textIdMaskapai = new javax.swing.JTextField();
        jNamaMaskapai = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jkeberangkatan = new javax.swing.JLabel();
        textKeb = new javax.swing.JTextField();
        jKedatangan = new javax.swing.JLabel();
        textKedatangan = new javax.swing.JTextField();
        jmaskapai = new javax.swing.JLabel();
        jwaktuKeb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMaskapai = new javax.swing.JTable();
        textwaktuBerangkat = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jwaktuked = new javax.swing.JLabel();
        textWaktuDatang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboJadwal = new javax.swing.JComboBox<>();
        jharga_bis = new javax.swing.JLabel();
        textHargaBisnis = new javax.swing.JTextField();
        jharga_eko = new javax.swing.JLabel();
        textHargaEkonomi = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Booking = new javax.swing.JMenuItem();
        Data = new javax.swing.JMenuItem();
        Jadwal = new javax.swing.JMenuItem();
        Maskapai = new javax.swing.JMenuItem();
        Payment = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIDmaskapai1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jIDmaskapai1.setText("ID maskapai");

        jNamaMaskapai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jNamaMaskapai.setText("Nama Maskapai");

        jkeberangkatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jkeberangkatan.setText("Keberangkatan");

        jKedatangan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jKedatangan.setText("Kedatangan");

        jmaskapai.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jmaskapai.setText("Pengaturan Maskapai");

        jwaktuKeb.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jwaktuKeb.setText("Waktu Keberangkatan");

        TableMaskapai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableMaskapai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMaskapaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMaskapai);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jwaktuked.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jwaktuked.setText("Waktu Kedatangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel1.setText("Jadwal");

        comboJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboJadwal.setSelectedIndex(-1);
        comboJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboJadwalMouseClicked(evt);
            }
        });
        comboJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJadwalActionPerformed(evt);
            }
        });

        jharga_bis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jharga_bis.setText("Harga Bisnis");

        jharga_eko.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jharga_eko.setText("Harga Ekonomi");

        jMenu4.setText("File");

        jMenuItem8.setText("Exit");
        jMenu4.add(jMenuItem8);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        Booking.setText("FrmBooking");
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });
        jMenu5.add(Booking);

        Data.setText("FrmData");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });
        jMenu5.add(Data);

        Jadwal.setText("FrmJadwal");
        Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalActionPerformed(evt);
            }
        });
        jMenu5.add(Jadwal);

        Maskapai.setText("FrmMaskapai");
        Maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaskapaiActionPerformed(evt);
            }
        });
        jMenu5.add(Maskapai);

        Payment.setText("FrmPayment");
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        jMenu5.add(Payment);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jmaskapai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jharga_bis)
                                    .addComponent(jharga_eko))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHargaEkonomi)
                                    .addComponent(textHargaBisnis)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNamaMaskapai)
                                    .addComponent(jIDmaskapai1)
                                    .addComponent(jKedatangan)
                                    .addComponent(jwaktuKeb)
                                    .addComponent(jkeberangkatan)
                                    .addComponent(jwaktuked))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textwaktuBerangkat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textKedatangan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textKeb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIdMaskapai)
                                    .addComponent(textWaktuDatang)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(simpan))
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hapus)
                                        .addGap(85, 85, 85))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(comboJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jmaskapai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIDmaskapai1)
                    .addComponent(textIdMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaMaskapai)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkeberangkatan)
                    .addComponent(textKeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKedatangan)
                    .addComponent(textKedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jwaktuKeb)
                    .addComponent(textwaktuBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textWaktuDatang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jwaktuked))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textHargaBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textHargaEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jharga_eko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan)
                            .addComponent(Tambah)
                            .addComponent(hapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jharga_bis)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
        FrmBooking frmBooking = new FrmBooking();
        frmBooking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookingActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
        FrmData frmdata = new FrmData();
        frmdata.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DataActionPerformed

    private void JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalActionPerformed
        // TODO add your handling code here:
        FrmJadwal frmjadwal = new FrmJadwal();
        frmjadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JadwalActionPerformed

    private void MaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaskapaiActionPerformed
        // TODO add your handling code here:
        FrmMaskapai frmmaskapai = new FrmMaskapai();
        frmmaskapai.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MaskapaiActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_TambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        
        Maskapai m = new Maskapai();
        m.setIdMaskapai(Integer.parseInt(textIdMaskapai.getText()));
        m.setNama(textNama.getText());
        m.setWaktuDeparture(textwaktuBerangkat.getText());
        m.setWaktuDestination(textWaktuDatang.getText());
        m.setJadwal((Jadwal)comboJadwal.getSelectedItem());
        m.setHarga_bis(Double.valueOf(textHargaBisnis.getText()));
        m.setHarga_eko(Double.valueOf(textHargaEkonomi.getText()));
        m.save();
        textIdMaskapai.setText(Integer.toString(m.getIdMaskapai()));
        tampilkanData();
        
    }//GEN-LAST:event_simpanActionPerformed

    private void comboJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboJadwalMouseClicked
        // TODO add your handling code here:
        Jadwal j = (Jadwal)comboJadwal.getSelectedItem();
        textKeb.setText(j.getDepature());
        textKedatangan.setText(j.getDestination());
    }//GEN-LAST:event_comboJadwalMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if (click) {
            DefaultTableModel model = (DefaultTableModel)TableMaskapai.getModel();
            int row = TableMaskapai.getSelectedRow();
            Maskapai m = new Maskapai().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
            m.delete();
            kosongkan();
            tampilkanData();
        }else {
            
        }
        
    }//GEN-LAST:event_hapusActionPerformed

    private void TableMaskapaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMaskapaiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TableMaskapai.getModel();
        int row = TableMaskapai.getSelectedRow();
        Maskapai m = new Maskapai().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        textIdMaskapai.setText(String.valueOf(m.getIdMaskapai()));
        textNama.setText(m.getNama());
        comboJadwal.getModel().setSelectedItem(m.getJadwal());
        textKedatangan.setText(m.getJadwal().getDestination());
        textKeb.setText(m.getJadwal().getDepature());
        textWaktuDatang.setText(String.valueOf(m.getWaktuDestination()));
        textwaktuBerangkat.setText(String.valueOf(m.getWaktuDeparture()));
        textHargaBisnis.setText(String.valueOf(m.getHarga_bis()));
        textHargaEkonomi.setText(String.valueOf(m.getHarga_eko()));
        click = true;
    }//GEN-LAST:event_TableMaskapaiMouseClicked

    private void comboJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMaskapai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Booking;
    private javax.swing.JMenuItem Data;
    private javax.swing.JMenuItem Jadwal;
    private javax.swing.JMenuItem Maskapai;
    private javax.swing.JMenuItem Payment;
    private javax.swing.JTable TableMaskapai;
    private javax.swing.JButton Tambah;
    private javax.swing.JComboBox<String> comboJadwal;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jIDmaskapai1;
    private javax.swing.JLabel jKedatangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel jNamaMaskapai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jharga_bis;
    private javax.swing.JLabel jharga_eko;
    private javax.swing.JLabel jkeberangkatan;
    private javax.swing.JLabel jmaskapai;
    private javax.swing.JLabel jwaktuKeb;
    private javax.swing.JLabel jwaktuked;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField textHargaBisnis;
    private javax.swing.JTextField textHargaEkonomi;
    private javax.swing.JTextField textIdMaskapai;
    private javax.swing.JTextField textKeb;
    private javax.swing.JTextField textKedatangan;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textWaktuDatang;
    private javax.swing.JTextField textwaktuBerangkat;
    // End of variables declaration//GEN-END:variables
}
